import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { listAdminProposals } from "@/lib/repository";
import { createManagedWebsite } from "../../actions";
import styles from "@/components/admin/Admin.module.css";

export default async function NewWebsitePage({ searchParams }: { searchParams: Promise<{ error?: string; proposal?: string }> }) {
  const { error, proposal } = await searchParams; const proposals = await listAdminProposals();
  return <><Link className={styles.back} href="/admin/dominios"><ArrowLeft size={18} /> Volver a dominios</Link><h1>Nueva web contratada</h1><p className="muted">Registra la puesta en marcha y empieza a controlar dominios y mantenimiento.</p>{error && <p className="notice error-notice">No se han podido guardar los datos. Revisa los campos.</p>}<form className={styles.panel} action={createManagedWebsite}><div className={styles.field}><label htmlFor="businessName">Nombre del negocio</label><input className={styles.input} id="businessName" name="businessName" placeholder="Ej. Restaurante Paco" /><span className="muted">Déjalo vacío si vinculas una propuesta existente.</span></div><div className={styles.field}><label htmlFor="proposalId">Negocio o propuesta existente (opcional)</label><select className={styles.select} id="proposalId" name="proposalId" defaultValue={proposal || ""}><option value="">Crear ficha nueva</option>{proposals.map((item) => <option value={item.id} key={item.id}>{item.businessName} · {item.slug || "sin slug"}</option>)}</select></div><input type="hidden" name="businessId" value="" /><div className={styles.field}><label htmlFor="websiteUrl">URL de la web</label><input className={styles.input} id="websiteUrl" name="websiteUrl" placeholder="https://ejemplo.es" inputMode="url" /></div><div className={styles.grid2}><div className={styles.field}><label htmlFor="activatedOn">Web operativa desde</label><input className={styles.input} id="activatedOn" name="activatedOn" type="date" /></div><div className={styles.field}><label htmlFor="maintenanceMonthly">Cuota mensual (€)</label><input className={styles.input} id="maintenanceMonthly" name="maintenanceMonthly" inputMode="decimal" placeholder="39" /></div></div><div className={styles.field}><label htmlFor="notes">Notas internas</label><textarea className={styles.textarea} id="notes" name="notes" placeholder="Condiciones, persona de contacto o detalles del servicio" /></div><button className="button button-primary" type="submit">Guardar web</button></form></>;
}
