import Link from "next/link";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { notFound } from "next/navigation";
import { getAdminWebsite } from "@/lib/repository";
import { formatCalendarDate, formatEuroCents } from "@/lib/admin-content";
import { anniversaryDate } from "@/lib/domains";
import { archiveManagedWebsite, registerMaintenancePayment, saveManagedDomain, updateManagedWebsite, voidMaintenancePayment } from "../../actions";
import styles from "@/components/admin/Admin.module.css";

function statusText(status: string) { return ({ active: "Vigente", soon: "Renueva en 30 días", today: "Renueva hoy", overdue: "Vencido", unknown: "Sin fecha" } as Record<string, string>)[status] || status; }

export default async function WebsiteDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const website = await getAdminWebsite(id); if (!website) notFound();
  const firstStart = website.activatedOn || new Date().toISOString().slice(0, 10);
  return <>
    <Link className={styles.back} href="/admin/dominios"><ArrowLeft size={18} /> Volver a dominios</Link>
    <div className={styles.topline}><div><h1>{website.businessName}</h1><p>{website.websiteUrl || "URL pendiente"} · Web contratada</p></div><span className={styles.tag}>{website.archived ? "Archivada" : website.activeDays === undefined ? "Pendiente de activar" : "Activa"}</span></div>
    <section className={styles.stats} aria-label="Resumen de mantenimiento"><div className={styles.stat}><strong>{website.activeDays === undefined ? "—" : website.activeDays}</strong><span>Días activa</span></div><div className={styles.stat}><strong>{website.activeDays === undefined ? "—" : `${website.completeMonths} + ${website.remainingDays} d`}</strong><span>Meses completos + días</span></div><div className={styles.stat}><strong>{website.paidMonths}</strong><span>Meses pagados</span></div><div className={styles.stat}><strong>{website.pendingMonths}</strong><span>Meses pendientes</span></div></section>
    <div className={styles.detailGrid}><div className={styles.detailMain}>
      <section className={styles.panel}><h2>Datos de la web</h2><form action={updateManagedWebsite}><input type="hidden" name="id" value={website.id} /><input type="hidden" name="businessId" value={website.businessId || ""} /><input type="hidden" name="businessName" value={website.businessName} /><input type="hidden" name="proposalId" value={website.proposalId || ""} /><div className={styles.field}><label htmlFor="websiteUrl">URL de la web</label><input className={styles.input} id="websiteUrl" name="websiteUrl" defaultValue={website.websiteUrl} /></div><div className={styles.grid2}><div className={styles.field}><label htmlFor="activatedOn">Operativa desde</label><input className={styles.input} id="activatedOn" name="activatedOn" type="date" defaultValue={website.activatedOn} /></div><div className={styles.field}><label htmlFor="maintenanceMonthly">Cuota mensual (€)</label><input className={styles.input} id="maintenanceMonthly" name="maintenanceMonthly" inputMode="decimal" defaultValue={website.maintenanceMonthlyCents === undefined ? "" : (website.maintenanceMonthlyCents / 100).toFixed(2)} /></div></div><div className={styles.field}><label htmlFor="notes">Notas internas</label><textarea className={styles.textarea} id="notes" name="notes" defaultValue={website.notes} /></div><button className="button button-secondary" type="submit">Guardar datos</button></form></section>
      <section className={styles.panel}><h2>Dominios</h2><div className={styles.list}>{website.domains.map((domain) => <div className={styles.row} key={domain.id}><span><strong>{domain.name}</strong><small>{domain.provider || "Proveedor sin indicar"} · {statusText(domain.renewalStatus)}</small></span><span><strong>{formatCalendarDate(domain.nextRenewalOn)}</strong><small>{domain.daysToRenewal === undefined ? "" : domain.daysToRenewal < 0 ? `${Math.abs(domain.daysToRenewal)} días vencido` : `${domain.daysToRenewal} días`}</small></span><span><small>{domain.autoRenew ? "Renovación automática" : "Renovación manual"}</small></span><span /></div>)}{website.domains.length === 0 && <p className="muted">Todavía no hay dominios registrados.</p>}</div><form action={saveManagedDomain} className={styles.panel} style={{ margin: "1rem 0 0", padding: "1rem", background: "#f8faf7" }}><input type="hidden" name="websiteId" value={website.id} /><input type="hidden" name="id" value="" /><h3>Añadir dominio</h3><div className={styles.grid2}><div className={styles.field}><label htmlFor="domainName">Dominio</label><input className={styles.input} id="domainName" name="name" placeholder="ejemplo.es" required /></div><div className={styles.field}><label htmlFor="provider">Proveedor</label><input className={styles.input} id="provider" name="provider" placeholder="DonDominio, IONOS..." /></div><div className={styles.field}><label htmlFor="contractedOn">Contratado el</label><input className={styles.input} id="contractedOn" name="contractedOn" type="date" /></div><div className={styles.field}><label htmlFor="nextRenewalOn">Próxima renovación</label><input className={styles.input} id="nextRenewalOn" name="nextRenewalOn" type="date" /></div></div><label className={styles.field}><span><input type="checkbox" name="autoRenew" /> Renovación automática</span></label><button className="button button-secondary" type="submit">Guardar dominio</button></form></section>
      {website.domains.map((domain) => <section className={styles.panel} key={`event-${domain.id}`}><h2>Factura o renovación · {domain.name}</h2>{domain.events && domain.events.length > 0 && <div className={styles.list}>{domain.events.map((event) => <div className={styles.row} key={event.id}><span><strong>{event.eventType === "renewal" ? "Renovación" : event.eventType === "purchase" ? "Compra" : "Movimiento"}</strong><small>{formatCalendarDate(event.eventDate)} · {event.provider || "Proveedor sin indicar"}</small></span><span><strong>{formatEuroCents(event.amountCents)}</strong><small>{event.notes || ""}</small></span><span>{event.fileId ? <a href={`/api/admin/dominios/facturas/${event.fileId}`}>{event.fileName || "Ver factura"}</a> : ""}</span><span /></div>)}</div>}<form action={`/api/admin/dominios/${domain.id}/factura`} method="post" encType="multipart/form-data"><input type="hidden" name="websiteId" value={website.id} /><input type="hidden" name="eventType" value="renewal" /><div className={styles.grid2}><div className={styles.field}><label htmlFor={`eventDate-${domain.id}`}>Fecha</label><input className={styles.input} id={`eventDate-${domain.id}`} name="eventDate" type="date" required /></div><div className={styles.field}><label htmlFor={`eventProvider-${domain.id}`}>Proveedor</label><input className={styles.input} id={`eventProvider-${domain.id}`} name="provider" defaultValue={domain.provider} /></div><div className={styles.field}><label htmlFor={`eventAmount-${domain.id}`}>Importe (€)</label><input className={styles.input} id={`eventAmount-${domain.id}`} name="amount" inputMode="decimal" /></div><div className={styles.field}><label htmlFor={`invoice-${domain.id}`}>Factura (PDF, JPG o PNG · 10 MB)</label><input className={styles.input} id={`invoice-${domain.id}`} name="file" type="file" accept="application/pdf,image/jpeg,image/png" /></div></div><div className={styles.field}><label htmlFor={`eventNotes-${domain.id}`}>Notas</label><textarea className={styles.textarea} id={`eventNotes-${domain.id}`} name="notes" /></div><button className="button button-secondary" type="submit">Registrar renovación</button></form></section>)}
      <section className={styles.panel}><h2>Registrar cobro de mantenimiento</h2><p className="muted">Se asignan meses completos desde la fecha inicial elegida, aunque el cobro sea adelantado.</p><form action={registerMaintenancePayment}><input type="hidden" name="websiteId" value={website.id} /><div className={styles.grid2}><div className={styles.field}><label htmlFor="paidOn">Cobrado el</label><input className={styles.input} id="paidOn" name="paidOn" type="date" required /></div><div className={styles.field}><label htmlFor="amount">Importe (€)</label><input className={styles.input} id="amount" name="amount" inputMode="decimal" defaultValue={website.maintenanceMonthlyCents ? (website.maintenanceMonthlyCents * 3 / 100).toFixed(2) : ""} required /></div><div className={styles.field}><label htmlFor="periodStart">Primer periodo desde</label><input className={styles.input} id="periodStart" name="periodStart" type="date" defaultValue={firstStart} required /></div><div className={styles.field}><label htmlFor="monthsCovered">Meses cubiertos</label><input className={styles.input} id="monthsCovered" name="monthsCovered" type="number" min="1" max="60" defaultValue="1" required /></div></div><div className={styles.field}><label htmlFor="paymentNotes">Notas</label><textarea className={styles.textarea} id="paymentNotes" name="notes" /></div><button className="button button-primary" type="submit">Guardar cobro</button></form></section>
      <section className={styles.panel}><h2>Historial de cobros</h2><div className={styles.list}>{website.payments.map((payment) => <div className={styles.row} key={payment.id}><span><strong>{formatCalendarDate(payment.periodStart)} · {payment.monthsCovered} meses</strong><small>Cobrado el {formatCalendarDate(payment.paidOn)}{payment.voidedAt ? " · Anulado" : ""}</small></span><span><strong>{formatEuroCents(payment.amountCents)}</strong><small>{payment.notes || ""}</small></span><span />{!payment.voidedAt && <form action={voidMaintenancePayment}><input type="hidden" name="id" value={payment.id} /><input type="hidden" name="websiteId" value={website.id} /><button className="button button-secondary" type="submit">Anular</button></form>}</div>)}{website.payments.length === 0 && <p className="muted">Aún no hay cobros registrados.</p>}</div></section>
    <section className={styles.panel}><h2>Editar dominios</h2>{website.domains.map((domain) => <form action={saveManagedDomain} key={`edit-${domain.id}`}><input type="hidden" name="websiteId" value={website.id} /><input type="hidden" name="id" value={domain.id} /><div className={styles.grid2}><div className={styles.field}><label htmlFor={`edit-name-${domain.id}`}>Dominio</label><input className={styles.input} id={`edit-name-${domain.id}`} name="name" defaultValue={domain.name} /></div><div className={styles.field}><label htmlFor={`edit-provider-${domain.id}`}>Proveedor</label><input className={styles.input} id={`edit-provider-${domain.id}`} name="provider" defaultValue={domain.provider} /></div><div className={styles.field}><label htmlFor={`edit-contracted-${domain.id}`}>Contratado el</label><input className={styles.input} id={`edit-contracted-${domain.id}`} name="contractedOn" type="date" defaultValue={domain.contractedOn} /></div><div className={styles.field}><label htmlFor={`edit-renewal-${domain.id}`}>Próxima renovación</label><input className={styles.input} id={`edit-renewal-${domain.id}`} name="nextRenewalOn" type="date" defaultValue={domain.nextRenewalOn} /></div></div><label className={styles.field}><span><input type="checkbox" name="autoRenew" defaultChecked={domain.autoRenew} /> Renovación automática</span></label><button className="button button-secondary" type="submit">Actualizar dominio</button></form>)}</section><aside><section className={`${styles.panel} ${styles.linksPanel}`}><h2>Resumen económico</h2><dl className={styles.definition}><dt>Total cobrado</dt><dd>{formatEuroCents(website.totalPaidCents)}</dd><dt>Cuota mensual</dt><dd>{formatEuroCents(website.maintenanceMonthlyCents)}</dd><dt>Inicio</dt><dd>{formatCalendarDate(website.activatedOn)}</dd><dt>Próximo mes pendiente</dt><dd>{website.activatedOn && website.pendingMonths > 0 ? formatCalendarDate(anniversaryDate(website.activatedOn, website.paidMonths)) : "Al día"}</dd></dl>{website.websiteUrl && <a className="button button-secondary" href={website.websiteUrl} target="_blank" rel="noreferrer">Abrir web <ExternalLink size={16} aria-hidden="true" /></a>}</section><section className={styles.panel}><h2>Acciones</h2>{!website.archived && <form action={archiveManagedWebsite}><input type="hidden" name="id" value={website.id} /><button className="button button-secondary" type="submit">Archivar web</button></form>}</section></aside></div>
    </div>
  </>;
}
