create extension if not exists pgcrypto;
create extension if not exists unaccent;
create type proposal_stage as enum ('draft','prepared','sent','archived');
create type commercial_status as enum ('unclassified','pending_contact','contacted','waiting','interested','client','not_interested');
create type response_intent as enum ('information','changes','talk','share','opinion','demo_help','decline');
create type followup_state as enum ('none','pending','attended');

create table if not exists admin_users (id uuid primary key default gen_random_uuid(), google_sub text unique, email text not null unique, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists sessions (id uuid primary key default gen_random_uuid(), admin_id uuid not null references admin_users(id) on delete cascade, token_hash text not null unique, expires_at timestamptz not null, created_at timestamptz not null default now());
create table if not exists businesses (id uuid primary key default gen_random_uuid(), name text, business_type text, known_contact_name text, known_contact_email text, known_contact_phone text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists proposals (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete restrict, slug text unique, public_token text not null unique, demo_url text, form_version integer not null default 1, stage proposal_stage not null default 'draft', commercial_status commercial_status not null default 'unclassified', is_active boolean not null default false, activated_at timestamptz, sent_at timestamptz, next_contact_at timestamptz, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists responses (id uuid primary key default gen_random_uuid(), proposal_id uuid not null references proposals(id) on delete cascade, request_id uuid not null, form_version integer not null, pricing_version integer not null default 1, answers jsonb not null, intent response_intent not null, impression text, goal text, selected_plan text, respondent_name text, relationship text, decision_role text, decline_reason text, is_read boolean not null default false, followup_status followup_state not null default 'none', created_at timestamptz not null default now(), unique(proposal_id,request_id));
create table if not exists response_contacts (response_id uuid primary key references responses(id) on delete cascade, method text not null, contact_value text, preferred_time text, preferred_datetime timestamptz, relay_email text);
create table if not exists domain_preferences (response_id uuid primary key references responses(id) on delete cascade, status text not null, current_domain text, desired_domains text[] not null default '{}');
create table if not exists response_changes (response_id uuid not null references responses(id) on delete cascade, category text not null, primary key(response_id,category));
create table if not exists pricing_versions (version integer primary key, content jsonb not null, active_from timestamptz not null default now(), active_until timestamptz);
create table if not exists notes (id uuid primary key default gen_random_uuid(), proposal_id uuid not null references proposals(id) on delete cascade, response_id uuid references responses(id) on delete cascade, author_id uuid not null references admin_users(id), body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists followups (id uuid primary key default gen_random_uuid(), proposal_id uuid not null references proposals(id) on delete cascade, response_id uuid references responses(id) on delete set null, author_id uuid not null references admin_users(id), channel text not null, result text not null, contacted_at timestamptz not null default now(), next_contact_at timestamptz);
create table if not exists rate_limit_events (id bigserial primary key, proposal_id uuid not null references proposals(id) on delete cascade, origin_hash text not null, created_at timestamptz not null default now());
create table if not exists managed_websites (id uuid primary key default gen_random_uuid(), business_id uuid references businesses(id) on delete restrict, proposal_id uuid references proposals(id) on delete set null, website_url text, activated_on date, deactivated_on date, maintenance_monthly_cents integer, notes text, archived boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists managed_domains (id uuid primary key default gen_random_uuid(), website_id uuid not null references managed_websites(id) on delete cascade, name text not null, provider text, contracted_on date, next_renewal_on date, auto_renew boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists domain_events (id uuid primary key default gen_random_uuid(), domain_id uuid not null references managed_domains(id) on delete cascade, event_type text not null, event_date date not null, provider text, amount_cents integer, notes text, file_path text, file_name text, file_mime text, file_size integer, created_at timestamptz not null default now());
create table if not exists maintenance_payments (id uuid primary key default gen_random_uuid(), website_id uuid not null references managed_websites(id) on delete cascade, paid_on date not null, amount_cents integer not null, notes text, voided_at timestamptz, created_at timestamptz not null default now());
create table if not exists maintenance_payment_periods (id uuid primary key default gen_random_uuid(), payment_id uuid not null references maintenance_payments(id) on delete cascade, website_id uuid not null references managed_websites(id) on delete cascade, period_start date not null, period_end date not null, unique(website_id,period_start));

create or replace view proposal_overview as select p.*, b.name business_name, b.business_type, lower(unaccent(coalesce(b.name,''))) business_search_name, b.known_contact_name, b.known_contact_email, b.known_contact_phone, (select count(*) from responses r where r.proposal_id=p.id) response_count, (select count(*) from responses r where r.proposal_id=p.id and not r.is_read) unread_count from proposals p join businesses b on b.id=p.business_id;
create or replace view response_overview as select r.*, b.name business_name, lower(unaccent(coalesce(b.name,''))) business_search_name, c.method contact_method, c.contact_value from responses r join proposals p on p.id=r.proposal_id join businesses b on b.id=p.business_id left join response_contacts c on c.response_id=r.id;
create or replace view managed_websites_view as select mw.*, b.name business_name from managed_websites mw left join businesses b on b.id=mw.business_id;
create index if not exists proposals_slug_idx on proposals(slug); create index if not exists responses_created_idx on responses(created_at desc); create index if not exists rate_limit_idx on rate_limit_events(origin_hash,created_at); create index if not exists domains_renewal_idx on managed_domains(next_renewal_on);
